export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_FULLFILLED = "FETCH_USERS_FULLFILLED";
export const FETCH_USERS_REJECTED = "FETCH_USERS_REJECTED";

export const LOCALDATA = "LOCALDATA";
